# Project information
site_name: 'SVGtoPPT'
site_description: 'Official homepage of SVGtoPPT'
site_url: 'https://svgtoppt.com'

# Repository
repo_name: SVGtoPPT/svgtoppt
repo_url: https://github.com/SVGtoPPT/svgtoppt
edit_uri: ''

nav:
  - Home: index.md
  - CLI: cli.md
  - Alfred: alfred.md
  - Support: support.md
  - About: about.md

copyright:
extra:
  form_action: https://formspree.io/f/xvovjejv
  search:
    tokenizer: '[\s\-\.]+'
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/blakegearin
    - icon: fontawesome/solid/house
      link: https://blakegearin.com

# Configuration
theme:
  name: 'material'
  custom_dir: 'theme'
  favicon: 'img/svgtoppt-icon.svg'
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
  language: 'en'
  font:
    text: 'Ubuntu'
    code: 'Roboto Mono'
  static_templates:
    - 404.html
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: fontawesome/solid/moon
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to light mode

extra_css:
  - stylesheets/colors.css
  - stylesheets/form.css
  - stylesheets/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js

plugins:
  - macros

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true
  - codehilite:
      linenums: false
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: false
