name: ci
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  schedule:
    - cron: '0 6 1 1 *'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install git+https://github.com/squidfunk/mkdocs-material.git
      - run: pip install mkdocs-macros-plugin
      - run: mkdocs gh-deploy --force
